package main

import (
	"fmt"
	"net"
	"runtime"
	"time"

	"github.com/rodrigocfd/windigo/ui"
	"github.com/rodrigocfd/windigo/co"
	"github.com/rodrigocfd/windigo/win"
)

var (
	mainWnd   *ui.Main
	tabMain   *ui.Tab
	chkAuto   *ui.CheckBox
	btnBatch  *ui.Button
	btnClear  *ui.Button
	btnQuit   *ui.Button
	lstDrafts *ui.ListView
	txtLog    *ui.Edit

	txtTemplate     *ui.Edit
	btnSaveTemplate *ui.Button

	autoSendEnabled = false
)

func GetAutoSend() bool {
	return autoSendEnabled
}

func SetAutoSend(b bool) {
	autoSendEnabled = b
}

func main() {
	runtime.LockOSThread()

	listener, err := net.Listen("tcp", "0.0.0.0:8081")
	if err != nil {
		win.HWND(0).MessageBox("无法绑定端口 8081 (报错: "+err.Error()+")。\nCode-Shield 通知工具可能已经在运行中，或者端口被占用。\n\nFailed to bind port 8081. Is notifier already running?", "启动失败 / Startup Failed", co.MB_OK|co.MB_ICONERROR)
		return
	}

	mainWnd = ui.NewMain(
		ui.OptsMain().
			Title("Code-Shield Notifier").
			Size(640, 560),
	)

	setupControls()
	setupEvents()

	go StartHTTPServer(listener)

	mainWnd.RunAsMain()
}

func setupControls() {
	tabMain = ui.NewTab(mainWnd, ui.OptsTab().
		Titles("常规态与日志", "邮件模版设置").
		Position(10, 10).
		Size(620, 540))

	tabOverview := tabMain.Item(0).Child()

	chkAuto = ui.NewCheckBox(tabOverview, ui.OptsCheckBox().
		Text("自动发送").
		Position(10, 10).
		Size(80, 20))

	btnBatch = ui.NewButton(tabOverview, ui.OptsButton().
		Text("批量发送等待中的邮件").
		Position(100, 8).
		Width(150).Height(24))

	btnClear = ui.NewButton(tabOverview, ui.OptsButton().
		Text("清空全部记录").
		Position(260, 8).
		Width(100).Height(24))

	btnQuit = ui.NewButton(tabOverview, ui.OptsButton().
		Text("退出程序").
		Position(490, 8).
		Width(100).Height(24))

	lstDrafts = ui.NewListView(tabOverview, ui.OptsListView().
		Position(10, 40).
		Size(590, 310).
		Column("状态", 60).
		Column("收件人", 150).
		Column("主题", 220).
		Column("时间", 120))

	txtLog = ui.NewEdit(tabOverview, ui.OptsEdit().
		Position(10, 360).
		Width(590).Height(140).
		CtrlStyle(co.ES_MULTILINE | co.ES_READONLY | co.ES_AUTOVSCROLL | co.ES_NOHIDESEL).
		WndStyle(co.WS_CHILD | co.WS_VISIBLE | co.WS_TABSTOP | co.WS_GROUP | co.WS_VSCROLL))

	tabSettings := tabMain.Item(1).Child()

	txtTemplate = ui.NewEdit(tabSettings, ui.OptsEdit().
		Position(10, 10).
		Width(590).Height(450).
		CtrlStyle(co.ES_MULTILINE | co.ES_WANTRETURN | co.ES_AUTOVSCROLL | co.ES_NOHIDESEL).
		WndStyle(co.WS_CHILD | co.WS_VISIBLE | co.WS_TABSTOP | co.WS_GROUP | co.WS_VSCROLL).
		Text(LoadTemplate()))

	btnSaveTemplate = ui.NewButton(tabSettings, ui.OptsButton().
		Text("保存模版").
		Position(490, 470).
		Width(110).Height(26))
}

func setupEvents() {
	var nid win.NOTIFYICONDATA
	const WM_TRAYICON = co.WM_APP + 1

	mainWnd.On().WmCreate(func(p ui.WmCreate) int {
		chkAuto.SetCheck(GetAutoSend())

		nid.SetCbSize()
		nid.HWnd = mainWnd.Hwnd()
		nid.UID = 100
		nid.UFlags = co.NIF_MESSAGE | co.NIF_ICON | co.NIF_TIP
		nid.UCallbackMessage = WM_TRAYICON
		
		hInst, _ := win.GetModuleHandle("")
		// Try to load custom icon (ID 1 generated by rsrc)
		hIcon, err := hInst.LoadIcon(win.IconResId(1))
		if err != nil || hIcon == 0 {
			// Fallback to default application icon
			hIcon, _ = win.HINSTANCE(0).LoadIcon(win.IconResId(uint16(co.IDI_APPLICATION)))
		}
		nid.HIcon = hIcon
		nid.SetSzTip("Code-Shield Notifier (Running)")
		
		win.Shell_NotifyIcon(co.NIM_ADD, &nid)
		return 0
	})

	chkAuto.On().BnClicked(func() {
		state := chkAuto.IsChecked()
		SetAutoSend(state)
		if state {
			LogMessage("Auto-send enabled.")
		} else {
			LogMessage("Auto-send disabled.")
		}
	})

	btnBatch.On().BnClicked(func() {
		LogMessage("Checking Outlook Drafts for batch sending...")
		go func() {
			defer func() {
				if r := recover(); r != nil {
					LogMessage(fmt.Sprintf("Batch Send Panic: %v", r))
				}
			}()

			sentCount, err := BatchSendOutlookDrafts()
			if err != nil {
				LogMessage(fmt.Sprintf("Batch send error: %v", err))
			} else {
				LogMessage(fmt.Sprintf("Batch send complete: Sent %d matching emails from Outlook Drafts.", sentCount))
			}
		}()
	})

	btnClear.On().BnClicked(func() {
		if mainWnd != nil && mainWnd.Hwnd() != 0 {
			mainWnd.UiThread(func() {
				lstDrafts.DeleteAllItems()
			})
		}
		LogMessage("Local GUI draft history cleared.")
	})

	btnQuit.On().BnClicked(func() {
		mainWnd.Hwnd().DestroyWindow()
	})

	btnSaveTemplate.On().BnClicked(func() {
		err := SaveTemplate(txtTemplate.Text())
		if err != nil {
			win.HWND(mainWnd.Hwnd()).MessageBox("保存失败: "+err.Error(), "错误", co.MB_OK|co.MB_ICONERROR)
		} else {
			win.HWND(mainWnd.Hwnd()).MessageBox("模版保存成功！\n注意：当前修改立即生效。", "保存成功", co.MB_OK|co.MB_ICONINFORMATION)
		}
	})




	mainWnd.On().Wm(WM_TRAYICON, func(p ui.Wm) uintptr {
		lParam := co.WM(p.LParam)
		if lParam == co.WM_LBUTTONDBLCLK || lParam == co.WM_LBUTTONUP {
			mainWnd.Hwnd().ShowWindow(co.SW_RESTORE)
			mainWnd.Hwnd().SetForegroundWindow()
		}
		return 0
	})

	mainWnd.On().Wm(co.WM_CLOSE, func(p ui.Wm) uintptr {
		mainWnd.Hwnd().ShowWindow(co.SW_HIDE)
		return 0 // intercept and don't destroy
	})

	mainWnd.On().WmDestroy(func() {
		win.Shell_NotifyIcon(co.NIM_DELETE, &nid)
	})
}

func LogMessage(msg string) {
	fmt.Println(msg)
	if mainWnd == nil || mainWnd.Hwnd() == 0 {
		return
	}
	mainWnd.UiThread(func() {
		t := time.Now().Format("15:04:05")
		current := txtLog.Text()
		
		if len(current) > 10000 {
			current = current[:10000]
		}
		
		txtLog.SetText(fmt.Sprintf("[%s] %s\r\n%s", t, msg, current))
	})
}

func AddDraftLogToView(status, to, subject, timeStr string) {
	if mainWnd == nil || mainWnd.Hwnd() == 0 {
		return
	}
	mainWnd.UiThread(func() {
		lstDrafts.AddItem(status, to, subject, timeStr)
	})
}
