package main

import (
	"fmt"
	"runtime"
	"time"

	"github.com/rodrigocfd/windigo/ui"
	"github.com/rodrigocfd/windigo/co"
	"github.com/rodrigocfd/windigo/win"
)

var (
	mainWnd   *ui.Main
	chkAuto   *ui.CheckBox
	btnBatch  *ui.Button
	btnClear  *ui.Button
	btnQuit   *ui.Button
	lstDrafts *ui.ListView
	txtLog    *ui.Edit

	autoSendEnabled = false
)

func GetAutoSend() bool {
	return autoSendEnabled
}

func SetAutoSend(b bool) {
	autoSendEnabled = b
}

func main() {
	runtime.LockOSThread()

	mainWnd = ui.NewMain(
		ui.OptsMain().
			Title("Code-Shield Notifier").
			Size(600, 500),
	)

	setupControls()
	setupEvents()

	go StartHTTPServer()

	mainWnd.RunAsMain()
}

func setupControls() {
	chkAuto = ui.NewCheckBox(mainWnd, ui.OptsCheckBox().
		Text("自动发送").
		Position(10, 10).
		Size(80, 20))

	btnBatch = ui.NewButton(mainWnd, ui.OptsButton().
		Text("批量发送等待中的邮件").
		Position(100, 8).
		Width(150).Height(24))

	btnClear = ui.NewButton(mainWnd, ui.OptsButton().
		Text("清空全部记录").
		Position(260, 8).
		Width(100).Height(24))

	btnQuit = ui.NewButton(mainWnd, ui.OptsButton().
		Text("退出程序").
		Position(490, 8).
		Width(100).Height(24))

	lstDrafts = ui.NewListView(mainWnd, ui.OptsListView().
		Position(10, 40).
		Size(580, 290).
		Column("状态", 60).
		Column("收件人", 150).
		Column("主题", 220).
		Column("时间", 120))

	txtLog = ui.NewEdit(mainWnd, ui.OptsEdit().
		Position(10, 340).
		Width(580).Height(150).
		CtrlStyle(co.ES_MULTILINE | co.ES_READONLY | co.ES_AUTOVSCROLL | co.ES_NOHIDESEL).
		WndStyle(co.WS_CHILD | co.WS_VISIBLE | co.WS_TABSTOP | co.WS_GROUP | co.WS_VSCROLL))
}

func setupEvents() {
	var nid win.NOTIFYICONDATA
	const WM_TRAYICON = co.WM_APP + 1

	mainWnd.On().WmCreate(func(p ui.WmCreate) int {
		chkAuto.SetCheck(GetAutoSend())

		nid.SetCbSize()
		nid.HWnd = mainWnd.Hwnd()
		nid.UID = 100
		nid.UFlags = co.NIF_MESSAGE | co.NIF_ICON | co.NIF_TIP
		nid.UCallbackMessage = WM_TRAYICON
		
		hInst, _ := win.GetModuleHandle("")
		// Try to load custom icon (ID 1 generated by rsrc)
		hIcon, err := hInst.LoadIcon(win.IconResId(1))
		if err != nil || hIcon == 0 {
			// Fallback to default application icon
			hIcon, _ = win.HINSTANCE(0).LoadIcon(win.IconResId(uint16(co.IDI_APPLICATION)))
		}
		nid.HIcon = hIcon
		nid.SetSzTip("Code-Shield Notifier (Running)")
		
		win.Shell_NotifyIcon(co.NIM_ADD, &nid)
		return 0
	})

	chkAuto.On().BnClicked(func() {
		state := chkAuto.IsChecked()
		SetAutoSend(state)
		if state {
			LogMessage("Auto-send enabled.")
		} else {
			LogMessage("Auto-send disabled.")
		}
	})

	btnBatch.On().BnClicked(func() {
		LogMessage("Checking Outlook Drafts for batch sending...")
		go func() {
			sentCount, err := BatchSendOutlookDrafts()
			if err != nil {
				LogMessage(fmt.Sprintf("Batch send error: %v", err))
			} else {
				LogMessage(fmt.Sprintf("Batch send complete: Sent %d matching emails from Outlook Drafts.", sentCount))
			}
		}()
	})

	btnClear.On().BnClicked(func() {
		if mainWnd != nil && mainWnd.Hwnd() != 0 {
			mainWnd.UiThread(func() {
				lstDrafts.DeleteAllItems()
			})
		}
		LogMessage("Local GUI draft history cleared.")
	})

	btnQuit.On().BnClicked(func() {
		mainWnd.Hwnd().DestroyWindow()
	})




	mainWnd.On().Wm(WM_TRAYICON, func(p ui.Wm) uintptr {
		lParam := co.WM(p.LParam)
		if lParam == co.WM_LBUTTONDBLCLK || lParam == co.WM_LBUTTONUP {
			mainWnd.Hwnd().ShowWindow(co.SW_RESTORE)
			mainWnd.Hwnd().SetForegroundWindow()
		}
		return 0
	})

	mainWnd.On().Wm(co.WM_CLOSE, func(p ui.Wm) uintptr {
		mainWnd.Hwnd().ShowWindow(co.SW_HIDE)
		return 0 // intercept and don't destroy
	})

	mainWnd.On().WmDestroy(func() {
		win.Shell_NotifyIcon(co.NIM_DELETE, &nid)
	})
}

func LogMessage(msg string) {
	fmt.Println(msg)
	if mainWnd == nil || mainWnd.Hwnd() == 0 {
		return
	}
	mainWnd.UiThread(func() {
		t := time.Now().Format("15:04:05")
		current := txtLog.Text()
		
		if len(current) > 10000 {
			current = current[:10000]
		}
		
		txtLog.SetText(fmt.Sprintf("[%s] %s\r\n%s", t, msg, current))
	})
}

func AddDraftLogToView(status, to, subject, timeStr string) {
	if mainWnd == nil || mainWnd.Hwnd() == 0 {
		return
	}
	mainWnd.UiThread(func() {
		lstDrafts.AddItem(status, to, subject, timeStr)
	})
}
